version: 2
jobs:
  build:
    branches:
      only:
        - Test
    docker:
      - image: circleci/jessie
        environment:
          TEST_DATABASE_URL: postgresql://admin:admin@localhost/thunderstorm
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: admin
          POSTGRES_DB: thunderstorm
          POSTGRES_PASSWORD: admin
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install wget zip unzip curl psmisc -y
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt install nodejs
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: run integration tests
          command: |
            pwd
            cd webapp/assignment2/
            npm install
            export RDS_USER_NAME=admin
            export RDS_PASSWORD=admin
            export RDS_CONNECTION_STRING=localhost
            export RDS_DB_NAME=thunderstorm
            export S3_BUCKET_NAME=tests.krishnavikas.me
            export PORT=3005
            npm start &
            sleep 10
            npm test
            killall npm
            rm -rf ./node_module*
            cd ../../
            pwd

      - run:
          name: install awscli
          command: sudo pip install awscli

      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            aws configure set default.region us-east-1
            pwd
            ls -al
            mkdir -p codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.sh .
            cp webapp/assignment2/cloudwatch-agent-config.json .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip webapp *.sh *.yml *.json
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al

      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp codedeploy_artifact/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip s3://${S3_BUCKET_ADDR}/deployments/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip

      - run:
          name: Make CodeDeploy API call
          command: |
            aws deploy create-deployment \
            --application-name csye6225-webapp \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name csye6225-webapp-deployment \
            --s3-location bucket=${S3_BUCKET_ADDR},bundleType=zip,key=deployments/csye6225-web-app-${CIRCLE_BUILD_NUM}.zip \
            --region us-east-1
